name: CI/CD

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: gke-net7-example
  CLUSTER_NAME: example-cluster
  REGION: us-east5
  CHART_PATH: gke-example-chart
  RELEASE_NAME: example-release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build and publish Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: gcr.io/${{ env.PROJECT_ID }}/my-app:${{ github.sha }}
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}
    - name: Configure Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1.1.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Configure kubectl
      uses: GoogleCloudPlatform/github-actions/setup-kubectl@master
      with:
        project_id: ${{ env.PROJECT_ID }}
        location: ${{ env.REGION }}
        cluster_name: ${{ env.CLUSTER_NAME }}
    - name: Deploy to GKE
      uses: GoogleCloudPlatform/github-actions/helm-deploy@v1.3.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        location: ${{ env.REGION }}
        cluster_name: ${{ env.CLUSTER_NAME }}
        namespace: default
        chart_path: ./${{ env.CLUSTER_NAME }}
        release_name: ${{env.RELEASE_NAME}}
        extra_args: --wait
